name: CI/CD Frontend Despacho

on:
  push:
    branches:
      - deploy

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Desplegar en EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_FRONTEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "sudo yum install docker -y",
              "sudo systemctl start docker",
              "sudo systemctl enable docker",
              "sudo docker stop front-despacho || true",
              "sudo docker rm front-despacho || true",
              "sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest",
              "sudo docker run -d --name front-despacho -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/front-despacho:latest"
            ]' \
            --region ${{ secrets.AWS_REGION }}